spring:
  application:
    name: trading-bot
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TradingBot_DB?serverTimezone=UTC&characterEncoding=UTF-8
    username: movingjin
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mvc:
    static-path-pattern: /resources/**
  main:
    allow-bean-definition-overriding: true
